export interface DefaultAuctionData {
  assetName: string
  mainCategory: string
  subCategory: string
  latLng: { latitude: number; longitude: number }
  location: string
  title: string
  price: number
}

export const IMAGES_STORAGE_PREFIX = 'https://cdn.tanna.app/biddo/assets'

export const DEFAULT_AUCTIONS_DATA: DefaultAuctionData[] = [
  {
    assetName: 'biddo-agriculture.jpg',
    mainCategory: 'Industrial Equipment',
    subCategory: 'Agricultural Equipment',
    latLng: { latitude: 37.7749295, longitude: -122.4194155 },
    location: 'San Francisco',
    title: 'Agriculture',
    price: 100,
  },
  {
    assetName: 'biddo-animal prod.jpg',
    mainCategory: 'Groceries',
    subCategory: 'Pet products',
    latLng: { latitude: 37.7749295, longitude: -122.4194155 },
    location: 'San Francisco',
    title: 'Pet products',
    price: 29,
  },
  {
    assetName: 'biddo-animal-prod.jpg',
    mainCategory: 'Groceries',
    subCategory: 'Pet products',
    latLng: { latitude: 37.7749295, longitude: -122.4194155 },
    location: 'San Francisco',
    title: 'Pet products',
    price: 20,
  },
  {
    assetName: 'biddo-antiq.png',
    mainCategory: 'Collectibles',
    subCategory: 'Antiques',
    latLng: { latitude: 37.7749295, longitude: -122.4194155 },
    location: 'San Francisco',
    title: 'Antiques',
    price: 1500,
  },
  {
    assetName: 'biddo-antique.jpg',
    mainCategory: 'Collectibles',
    subCategory: 'Antiques',
    latLng: { latitude: 37.7749295, longitude: -122.4194155 },
    location: 'San Francisco',
    title: 'My Antiques',
    price: 900,
  },
  {
    assetName: 'biddo-antique.webp',
    mainCategory: 'Collectibles',
    subCategory: 'Antiques',
    latLng: { latitude: 37.7749295, longitude: -122.4194155 },
    location: 'San Francisco',
    title: 'My Antique clock',
    price: 2000,
  },
  {
    assetName: 'biddo-Atlantic-Watches-For-Him.jpg',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Watches',
    latLng: { latitude: 37.7749295, longitude: -122.4194155 },
    location: 'San Francisco',
    title: 'Selling my watch',
    price: 200,
  },
  {
    assetName: 'biddo-audio eq.jpeg',
    mainCategory: 'Consumer Electronics',
    subCategory: 'Audio Equipment',
    latLng: { latitude: 37.7749295, longitude: -122.4194155 },
    location: 'San Francisco',
    title: 'Selling my DJ station',
    price: 450,
  },
  {
    assetName: 'biddo-audio.jpeg',
    mainCategory: 'Consumer Electronics',
    subCategory: 'Audio Equipment',
    latLng: { latitude: 37.7749295, longitude: -122.4194155 },
    location: 'San Francisco',
    title: 'Selling my DJ station',
    price: 200,
  },
  {
    assetName: 'biddo-bag.jpg',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Bags and Luggage',
    latLng: { latitude: 37.7749295, longitude: -122.4194155 },
    location: 'San Francisco',
    title: 'Selling my purse',
    price: 100,
  },
  {
    assetName: 'biddo-bag.webp',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Bags and Luggage',
    latLng: { latitude: 44.4267674, longitude: 26.1025384 },
    location: 'Bucharest',
    title: 'Selling bags',
    price: 300,
  },
  {
    assetName: 'biddo-bicycle.jpeg',
    mainCategory: 'Vehicles',
    subCategory: 'Bicycles',
    latLng: { latitude: 44.4267674, longitude: 26.1025384 },
    location: 'Bucharest',
    title: 'Selling my bike',
    price: 250,
  },
  {
    assetName: 'biddo-bicycle.jpg',
    mainCategory: 'Vehicles',
    subCategory: 'Bicycles',
    latLng: { latitude: 44.4267674, longitude: 26.1025384 },
    location: 'Bucharest',
    title: 'Selling my bikes',
    price: 500,
  },
  {
    assetName: 'biddo-board-games.jpeg',
    mainCategory: 'Toys and Games',
    subCategory: 'Board Games',
    latLng: { latitude: 44.4267674, longitude: 26.1025384 },
    location: 'Bucharest',
    title: 'Selling my board games',
    price: 100,
  },
  {
    assetName: 'biddo-board-games.png',
    mainCategory: 'Toys and Games',
    subCategory: 'Board Games',
    latLng: { latitude: 44.4267674, longitude: 26.1025384 },
    location: 'Bucharest',
    title: 'Selling my old board games',
    price: 90,
  },
  {
    assetName: 'biddo-board-games.webp',
    mainCategory: 'Toys and Games',
    subCategory: 'Board Games',
    latLng: { latitude: 44.4267674, longitude: 26.1025384 },
    location: 'Bucharest',
    title: 'Selling special board games',
    price: 49,
  },
  {
    assetName: 'biddo-boat.jpeg',
    mainCategory: 'Vehicles',
    subCategory: 'Boats and Watercraft',
    latLng: { latitude: 40.7127753, longitude: -74.0059728 },
    location: 'New York',
    title: 'Selling my boat',
    price: 1500,
  },
  {
    assetName: 'biddo-boat.jpg',
    mainCategory: 'Vehicles',
    subCategory: 'Boats and Watercraft',
    latLng: { latitude: 40.7127753, longitude: -74.0059728 },
    location: 'New York',
    title: 'Selling my small boat',
    price: 1200,
  },
  {
    assetName: 'biddo-camera.jpeg',
    mainCategory: 'Consumer Electronics',
    subCategory: 'Cameras And Accessories',
    latLng: { latitude: 40.7127753, longitude: -74.0059728 },
    location: 'New York',
    title: 'Selling my camera',
    price: 299,
  },
  {
    assetName: 'biddo-camera.png',
    mainCategory: 'Consumer Electronics',
    subCategory: 'Cameras And Accessories',
    latLng: { latitude: 40.7127753, longitude: -74.0059728 },
    location: 'New York',
    title: 'Selling my CANON camera',
    price: 180,
  },
  {
    assetName: 'biddo-car.jpg',
    mainCategory: 'Vehicles',
    subCategory: 'Cars',
    latLng: { latitude: 40.7127753, longitude: -74.0059728 },
    location: 'New York',
    title: 'My special car',
    price: 120000,
  },
  {
    assetName: 'biddo-car.webp',
    mainCategory: 'Vehicles',
    subCategory: 'Cars',
    latLng: { latitude: 40.7127753, longitude: -74.0059728 },
    location: 'New York',
    title: 'My super special car',
    price: 300000,
  },
  {
    assetName: 'biddo-car1.jpg',
    mainCategory: 'Vehicles',
    subCategory: 'Cars',
    latLng: { latitude: 40.7127753, longitude: -74.0059728 },
    location: 'New York',
    title: 'My car',
    price: 250000,
  },
  {
    assetName: 'biddo-cat.avif',
    mainCategory: 'Vehicles',
    subCategory: 'Cars',
    latLng: { latitude: 40.7127753, longitude: -74.0059728 },
    location: 'New York',
    title: 'My super car',
    price: 199000,
  },
  {
    assetName: 'biddo-cleaning prod.jpg',
    mainCategory: 'Groceries',
    subCategory: 'Cleaning products',
    latLng: { latitude: 52.52000659999999, longitude: 13.404954 },
    location: 'Berlin',
    title: 'Cleaning products',
    price: 99,
  },
  {
    assetName: 'biddo-cleaning-prod.jpg',
    mainCategory: 'Groceries',
    subCategory: 'Cleaning products',
    latLng: { latitude: 52.52000659999999, longitude: 13.404954 },
    location: 'Berlin',
    title: 'Cleaning products',
    price: 120,
  },
  {
    assetName: 'biddo-clothes.jpeg',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Clothing',
    latLng: { latitude: 52.52000659999999, longitude: 13.404954 },
    location: 'Berlin',
    title: 'Selling my shop clothes',
    price: 300,
  },
  {
    assetName: 'biddo-clothing.webp',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Clothing',
    latLng: { latitude: 52.52000659999999, longitude: 13.404954 },
    location: 'Berlin',
    title: 'Selling men clothes',
    price: 250,
  },
  {
    assetName: 'biddo-coins.jpg',
    mainCategory: 'Collectibles',
    subCategory: 'Coins',
    latLng: { latitude: 52.52000659999999, longitude: 13.404954 },
    location: 'Berlin',
    title: 'Selling men limited edition coins',
    price: 999,
  },
  {
    assetName: 'biddo-commercial prop.jpg',
    mainCategory: 'Real Estate',
    subCategory: 'Commercial Properties',
    latLng: { latitude: 52.52000659999999, longitude: 13.404954 },
    location: 'Berlin',
    title: 'Renting commercial property',
    price: 5000,
  },
  {
    assetName: 'biddo-commercial-properties-in-ahemedabad-res-management.webp',
    mainCategory: 'Real Estate',
    subCategory: 'Commercial Properties',
    latLng: { latitude: 52.52000659999999, longitude: 13.404954 },
    location: 'Berlin',
    title: 'Renting commercial property',
    price: 6500,
  },
  {
    assetName: 'biddo-couch.jpeg',
    mainCategory: 'Home and Garden',
    subCategory: 'Furniture',
    latLng: { latitude: 19.0759837, longitude: 72.8776559 },
    location: 'Mumbai',
    title: 'Selling my couch',
    price: 220,
  },
  {
    assetName: 'biddo-couch.jpg',
    mainCategory: 'Home and Garden',
    subCategory: 'Furniture',
    latLng: { latitude: 19.0759837, longitude: 72.8776559 },
    location: 'Mumbai',
    title: 'Selling my old couch',
    price: 170,
  },
  {
    assetName: 'biddo-couch1.jpg',
    mainCategory: 'Home and Garden',
    subCategory: 'Furniture',
    latLng: { latitude: 19.0759837, longitude: 72.8776559 },
    location: 'Mumbai',
    title: 'My old couch',
    price: 170,
  },
  {
    assetName: 'biddo-fridge.webp',
    mainCategory: 'Consumer Electronics',
    subCategory: 'Home Electronics',
    latLng: { latitude: 19.0759837, longitude: 72.8776559 },
    location: 'Mumbai',
    title: 'My small fridge',
    price: 100,
  },
  {
    assetName: 'biddo-frigde.avif',
    mainCategory: 'Consumer Electronics',
    subCategory: 'Home Electronics',
    latLng: { latitude: 19.0759837, longitude: 72.8776559 },
    location: 'Mumbai',
    title: 'Selling my fridge',
    price: 200,
  },
  {
    assetName: 'biddo-frozen pod.webp',
    mainCategory: 'Groceries',
    subCategory: 'Frozen',
    latLng: { latitude: 19.0759837, longitude: 72.8776559 },
    location: 'Mumbai',
    title: 'Frozen vegetables',
    price: 30,
  },
  {
    assetName: 'biddo-frozen.jpg',
    mainCategory: 'Groceries',
    subCategory: 'Frozen',
    latLng: { latitude: 19.0759837, longitude: 72.8776559 },
    location: 'Mumbai',
    title: 'Frozen vegetables',
    price: 45,
  },
  {
    assetName: 'biddo-fuites-veg.jpg',
    mainCategory: 'Groceries',
    subCategory: 'Fruits and vegetables',
    latLng: { latitude: 19.0759837, longitude: 72.8776559 },
    location: 'Mumbai',
    title: 'Fresh fruits and vegerables',
    price: 25,
  },
  {
    assetName: 'biddo-fuits-veg.jpg',
    mainCategory: 'Groceries',
    subCategory: 'Fruits and vegetables',
    latLng: { latitude: 25.2048493, longitude: 55.2707828 },
    location: 'Dubai',
    title: 'Fresh fruits and vegerables',
    price: 30,
  },
  {
    assetName: 'biddo-gardening tools.jpg',
    mainCategory: 'Home and Garden',
    subCategory: 'Gardening',
    latLng: { latitude: 25.2048493, longitude: 55.2707828 },
    location: 'Dubai',
    title: 'Gardening tools',
    price: 90,
  },
  {
    assetName: 'biddo-gardening.png',
    mainCategory: 'Home and Garden',
    subCategory: 'Gardening',
    latLng: { latitude: 25.2048493, longitude: 55.2707828 },
    location: 'Dubai',
    title: 'Gardening tools',
    price: 50,
  },
  {
    assetName: 'biddo-house.jpeg',
    mainCategory: 'Real Estate',
    subCategory: 'Residential Properties',
    latLng: { latitude: 25.2048493, longitude: 55.2707828 },
    location: 'Dubai',
    title: 'Selling new house',
    price: 250000,
  },
  {
    assetName: 'biddo-house.webp',
    mainCategory: 'Real Estate',
    subCategory: 'Residential Properties',
    latLng: { latitude: 25.2048493, longitude: 55.2707828 },
    location: 'Dubai',
    title: 'Selling new house',
    price: 350000,
  },
  {
    assetName: 'biddo-house1.jpg',
    mainCategory: 'Real Estate',
    subCategory: 'Residential Properties',
    latLng: { latitude: 25.2048493, longitude: 55.2707828 },
    location: 'Dubai',
    title: 'Selling my house',
    price: 150000,
  },
  {
    assetName: 'biddo-jew.webp',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Jewelry',
    latLng: { latitude: 25.2048493, longitude: 55.2707828 },
    location: 'Dubai',
    title: 'Selling my Jewelry',
    price: 1200,
  },
  {
    assetName: 'biddo-jewlery.jpg',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Jewelry',
    latLng: { latitude: 25.2048493, longitude: 55.2707828 },
    location: 'Dubai',
    title: 'Selling my Jewelry',
    price: 2400,
  },
  {
    assetName: 'biddo-kitchen.jpeg',
    mainCategory: 'Industrial Equipment',
    subCategory: 'Restaurant Equipment',
    latLng: { latitude: 25.2048493, longitude: 55.2707828 },
    location: 'Dubai',
    title: 'Selling Restaurant Equipment',
    price: 4500,
  },
  {
    assetName: 'biddo-kitchen.webp',
    mainCategory: 'Industrial Equipment',
    subCategory: 'Restaurant Equipment',
    latLng: { latitude: 25.2048493, longitude: 55.2707828 },
    location: 'Dubai',
    title: 'Selling Restaurant Equipment',
    price: 2500,
  },
  {
    assetName: 'biddo-kitchenware.avif',
    mainCategory: 'Home and Garden',
    subCategory: 'Kitchenware',
    latLng: { latitude: 35.6803997, longitude: 139.7690174 },
    location: 'Tokyo',
    title: 'Nice Kitchenware',
    price: 120,
  },
  {
    assetName: 'biddo-kitchenware.jpg',
    mainCategory: 'Home and Garden',
    subCategory: 'Kitchenware',
    latLng: { latitude: 35.6803997, longitude: 139.7690174 },
    location: 'Tokyo',
    title: 'Nice Kitchenware',
    price: 270,
  },
  {
    assetName: 'biddo-land.jpeg',
    mainCategory: 'Real Estate',
    subCategory: 'Land',
    latLng: { latitude: 35.6803997, longitude: 139.7690174 },
    location: 'Tokyo',
    title: 'Land for sale',
    price: 90000,
  },
  {
    assetName: 'biddo-land.jpg',
    mainCategory: 'Real Estate',
    subCategory: 'Land',
    latLng: { latitude: 35.6803997, longitude: 139.7690174 },
    location: 'Tokyo',
    title: 'Land for sale',
    price: 85000,
  },
  {
    assetName: 'biddo-lang.jpg',
    mainCategory: 'Real Estate',
    subCategory: 'Land',
    latLng: { latitude: 35.6803997, longitude: 139.7690174 },
    location: 'Tokyo',
    title: 'Land for sale',
    price: 75000,
  },
  {
    assetName: 'biddo-laptop.jpg',
    mainCategory: 'Consumer Electronics',
    subCategory: 'Laptops & Tablets',
    latLng: { latitude: 35.6803997, longitude: 139.7690174 },
    location: 'Tokyo',
    title: 'Selling my laptop',
    price: 800,
  },
  {
    assetName: 'biddo-laptop.webp',
    mainCategory: 'Consumer Electronics',
    subCategory: 'Laptops & Tablets',
    latLng: { latitude: 19.4326077, longitude: -99.133208 },
    location: 'Mexico City',
    title: 'Selling my laptop',
    price: 670,
  },
  {
    assetName: 'biddo-laptops.webp',
    mainCategory: 'Consumer Electronics',
    subCategory: 'Laptops & Tablets',
    latLng: { latitude: 19.4326077, longitude: -99.133208 },
    location: 'Mexico City',
    title: 'Selling cheap laptop',
    price: 300,
  },
  {
    assetName: 'biddo-lego.avif',
    mainCategory: 'Toys and Games',
    subCategory: 'LEGO Sets',
    latLng: { latitude: 19.4326077, longitude: -99.133208 },
    location: 'Mexico City',
    title: 'Selling new lego',
    price: 230,
  },
  {
    assetName: 'biddo-lego.jpg',
    mainCategory: 'Toys and Games',
    subCategory: 'LEGO Sets',
    latLng: { latitude: 19.4326077, longitude: -99.133208 },
    location: 'Mexico City',
    title: 'Selling new lego',
    price: 830,
  },
  {
    assetName: 'biddo-lego.png',
    mainCategory: 'Toys and Games',
    subCategory: 'LEGO Sets',
    latLng: { latitude: 19.4326077, longitude: -99.133208 },
    location: 'Mexico City',
    title: 'Selling new lego',
    price: 130,
  },
  {
    assetName: 'biddo-luggage.jpg',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Bags and Luggage',
    latLng: { latitude: 19.4326077, longitude: -99.133208 },
    location: 'Mexico City',
    title: 'Selling new luggages',
    price: 190,
  },
  {
    assetName: 'biddo-luggage.webp',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Bags and Luggage',
    latLng: { latitude: 19.4326077, longitude: -99.133208 },
    location: 'Mexico City',
    title: 'Selling new luggages',
    price: 99,
  },
  {
    assetName: 'biddo-medical eq.jpg',
    mainCategory: 'Industrial Equipment',
    subCategory: 'Medical Equipment',
    latLng: { latitude: 19.4326077, longitude: -99.133208 },
    location: 'Mexico City',
    title: 'Selling medial equipment',
    price: 9900,
  },
  {
    assetName: 'biddo-morotcycle.webp',
    mainCategory: 'Vehicles',
    subCategory: 'Motorcycles',
    latLng: { latitude: 19.4326077, longitude: -99.133208 },
    location: 'Mexico City',
    title: 'Selling my bike',
    price: 3200,
  },
  {
    assetName: 'biddo-motorcycle.jpeg',
    mainCategory: 'Vehicles',
    subCategory: 'Motorcycles',
    latLng: { latitude: 51.5072178, longitude: -0.1275862 },
    location: 'London',
    title: 'Selling my bike',
    price: 3700,
  },
  {
    assetName: 'biddo-motorcycle.jpg',
    mainCategory: 'Vehicles',
    subCategory: 'Motorcycles',
    latLng: { latitude: 51.5072178, longitude: -0.1275862 },
    location: 'London',
    title: 'Selling new custom bike',
    price: 8900,
  },
  {
    assetName: 'biddo-painting.avif',
    mainCategory: 'Art',
    subCategory: 'Paintings',
    latLng: { latitude: 51.5072178, longitude: -0.1275862 },
    location: 'London',
    title: 'Selling new painting',
    price: 150,
  },
  {
    assetName: 'biddo-painting.jpeg',
    mainCategory: 'Art',
    subCategory: 'Paintings',
    latLng: { latitude: 51.5072178, longitude: -0.1275862 },
    location: 'London',
    title: 'Selling my painting',
    price: 70,
  },
  {
    assetName: 'biddo-painting.webp',
    mainCategory: 'Art',
    subCategory: 'Paintings',
    latLng: { latitude: 51.5072178, longitude: -0.1275862 },
    location: 'London',
    title: 'My painting',
    price: 50,
  },
  {
    assetName: 'biddo-phon1.webp',
    mainCategory: 'Consumer Electronics',
    subCategory: 'Smartphones',
    latLng: { latitude: 51.5072178, longitude: -0.1275862 },
    location: 'London',
    title: 'My old phone',
    price: 50,
  },
  {
    assetName: 'biddo-phone.jpg',
    mainCategory: 'Consumer Electronics',
    subCategory: 'Smartphones',
    latLng: { latitude: 51.5072178, longitude: -0.1275862 },
    location: 'London',
    title: 'New Phone. Best condition',
    price: 650,
  },
  {
    assetName: 'biddo-phone.webp',
    mainCategory: 'Consumer Electronics',
    subCategory: 'Smartphones',
    latLng: { latitude: 51.5072178, longitude: -0.1275862 },
    location: 'London',
    title: 'New Phone.',
    price: 550,
  },
  {
    assetName: 'biddo-puzzle.jpg',
    mainCategory: 'Toys and Games',
    subCategory: 'Puzzles',
    latLng: { latitude: 51.5072178, longitude: -0.1275862 },
    location: 'London',
    title: 'New Christmas Puzzle',
    price: 40,
  },
  {
    assetName: 'biddo-puzzle1.jpg',
    mainCategory: 'Toys and Games',
    subCategory: 'Puzzles',
    latLng: { latitude: 51.5072178, longitude: -0.1275862 },
    location: 'London',
    title: 'New Puzzle',
    price: 35,
  },
  {
    assetName: 'biddo-rv van.jpeg',
    mainCategory: 'Vehicles',
    subCategory: 'RV and Campers',
    latLng: { latitude: 51.5072178, longitude: -0.1275862 },
    location: 'London',
    title: 'My old RV',
    price: 7500,
  },
  {
    assetName: 'biddo-rv.jpg',
    mainCategory: 'Vehicles',
    subCategory: 'RV and Campers',
    latLng: { latitude: 41.8967068, longitude: 12.4822025 },
    location: 'Rome',
    title: 'My special RV',
    price: 5500,
  },
  {
    assetName: 'biddo-sculpture.jpg',
    mainCategory: 'Art',
    subCategory: 'Sculptures',
    latLng: { latitude: 41.8967068, longitude: 12.4822025 },
    location: 'Rome',
    title: 'My sculpture',
    price: 2000,
  },
  {
    assetName: 'biddo-sculpture.webp',
    mainCategory: 'Art',
    subCategory: 'Sculptures',
    latLng: { latitude: 41.8967068, longitude: 12.4822025 },
    location: 'Rome',
    title: 'Custom sculpture',
    price: 2500,
  },
  {
    assetName: 'biddo-shoes.jpeg',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Shoes',
    latLng: { latitude: 41.8967068, longitude: 12.4822025 },
    location: 'Rome',
    title: 'Puma shoes',
    price: 170,
  },
  {
    assetName: 'biddo-shoes.webp',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Shoes',
    latLng: { latitude: 41.8967068, longitude: 12.4822025 },
    location: 'Rome',
    title: 'Kids shoes',
    price: 80,
  },
  {
    assetName: 'biddo-shoes1.webp',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Shoes',
    latLng: { latitude: 48.8575475, longitude: 2.3513765 },
    location: 'Paris',
    title: 'Shoes for sale',
    price: 95,
  },
  {
    assetName: 'biddo-sports-mem.jpg',
    mainCategory: 'Collectibles',
    subCategory: 'Sports Memorabilia',
    latLng: { latitude: 48.8575475, longitude: 2.3513765 },
    location: 'Paris',
    title: 'Signed sports memorabilia',
    price: 4000,
  },
  {
    assetName: 'biddo-sports.jpg',
    mainCategory: 'Collectibles',
    subCategory: 'Sports Memorabilia',
    latLng: { latitude: 48.8575475, longitude: 2.3513765 },
    location: 'Paris',
    title: 'Signed sports memorabilia',
    price: 3500,
  },
  {
    assetName: 'biddo-sports.webp',
    mainCategory: 'Collectibles',
    subCategory: 'Sports Memorabilia',
    latLng: { latitude: 48.8575475, longitude: 2.3513765 },
    location: 'Paris',
    title: 'Old Signed sports memorabilia',
    price: 5000,
  },
  {
    assetName: 'biddo-stamp.webp',
    mainCategory: 'Collectibles',
    subCategory: 'Stamps',
    latLng: { latitude: 48.8575475, longitude: 2.3513765 },
    location: 'Paris',
    title: 'Old Stamps',
    price: 400,
  },
  {
    assetName: 'biddo-stamps.jpg',
    mainCategory: 'Collectibles',
    subCategory: 'Stamps',
    latLng: { latitude: 37.56521290000001, longitude: 126.9773517 },
    location: 'Seoul',
    title: 'Collectible Stamps',
    price: 550,
  },
  {
    assetName: 'biddo-stamps.webp',
    mainCategory: 'Collectibles',
    subCategory: 'Stamps',
    latLng: { latitude: 37.56521290000001, longitude: 126.9773517 },
    location: 'Seoul',
    title: 'Collectible Stamps',
    price: 250,
  },
  {
    assetName: 'biddo-stamps1.webp',
    mainCategory: 'Collectibles',
    subCategory: 'Stamps',
    latLng: { latitude: 37.56521290000001, longitude: 126.9773517 },
    location: 'Seoul',
    title: 'My old Stamps',
    price: 200,
  },
  {
    assetName: 'biddo-tools.avif',
    mainCategory: 'Home and Garden',
    subCategory: 'Tools',
    latLng: { latitude: 37.56521290000001, longitude: 126.9773517 },
    location: 'Seoul',
    title: 'My tools',
    price: 180,
  },
  {
    assetName: 'biddo-tools.webp',
    mainCategory: 'Home and Garden',
    subCategory: 'Tools',
    latLng: { latitude: -6.1944491, longitude: 106.8229198 },
    location: 'Jakarta',
    title: 'My special tools',
    price: 220,
  },
  {
    assetName: 'biddo-tractor.avif',
    mainCategory: 'Industrial Equipment',
    subCategory: 'Agricultural Equipment',
    latLng: { latitude: -6.1944491, longitude: 106.8229198 },
    location: 'Jakarta',
    title: 'Selling my tractor',
    price: 4220,
  },
  {
    assetName: 'biddo-tractor.jpg',
    mainCategory: 'Industrial Equipment',
    subCategory: 'Agricultural Equipment',
    latLng: { latitude: 39.904211, longitude: 116.407395 },
    location: 'Beijing',
    title: 'My tractor',
    price: 5020,
  },
  {
    assetName: 'biddo-video game.png',
    mainCategory: 'Toys and Games',
    subCategory: 'Video Games',
    latLng: { latitude: 39.904211, longitude: 116.407395 },
    location: 'Beijing',
    title: 'Have to seel my video games',
    price: 320,
  },
  {
    assetName: 'biddo-video-game.avif',
    mainCategory: 'Toys and Games',
    subCategory: 'Video Games',
    latLng: { latitude: 39.904211, longitude: 116.407395 },
    location: 'Beijing',
    title: 'Old video games',
    price: 150,
  },
  {
    assetName: 'biddo-watch.webp',
    mainCategory: 'Fashion and Accessories',
    subCategory: 'Watches',
    latLng: { latitude: 39.904211, longitude: 116.407395 },
    location: 'Beijing',
    title: 'New watch',
    price: 470,
  },
]
