import sequelize from 'sequelize'
import { Category } from '../../modules/categories/model.js'
import { DATABASE_MODELS } from '../../constants/model-names.js'

const CATEGORIES = [
  {
    name: {
      en: 'Consumer Electronics',
      ro: 'Electronice',
      fr: 'Électronique grand public',
      de: 'Unterhaltungselektronik',
      it: 'Elettronica di consumo',
      es: 'Electrónica de consumo',
      ja: '家電製品',
    },
    icon: 'electronics',
    subCategories: [
      {
        name: {
          en: 'Smartphones',
          ro: 'Telefoane mobile',
          fr: 'Smartphones',
          de: 'Smartphones',
          it: 'Smartphone',
          es: 'Smartphones',
          ja: 'スマートフォン',
        },
        details: {
          en: 'Various brands, including accessories and spare parts',
          ro: 'Diverse branduri, inclusiv accesorii și piese de schimb',
          fr: 'Diverses marques, y compris accessoires et pièces de rechange',
          de: 'Verschiedene Marken, einschließlich Zubehör und Ersatzteile',
          it: 'Vari marchi, inclusi accessori e ricambi',
          es: 'Varias marcas, incluidos accesorios y repuestos',
          ja: 'さまざまなブランド、アクセサリーやスペアパーツを含む',
        },
      },
      {
        name: {
          en: 'Laptops & Tablets',
          ro: 'Laptopuri și tablete',
          fr: 'Ordinateurs portables et tablettes',
          de: 'Laptops und Tablets',
          it: 'Laptop e tablet',
          es: 'Portátiles y tabletas',
          ja: 'ノートパソコンとタブレット',
        },
        details: {
          en: 'Devices and peripherals',
          ro: 'Dispozitive și periferice',
          fr: 'Appareils et périphériques',
          de: 'Geräte und Peripheriegeräte',
          it: 'Dispositivi e periferiche',
          es: 'Dispositivos y periféricos',
          ja: 'デバイスと周辺機器',
        },
      },
      {
        name: {
          en: 'Cameras and Accessories',
          ro: 'Camere foto și accesorii',
          fr: 'Appareils photo et accessoires',
          de: 'Kameras und Zubehör',
          it: 'Fotocamere e accessori',
          es: 'Cámaras y accesorios',
          ja: 'カメラとアクセサリー',
        },
        details: {
          en: 'Digital cameras, lenses, tripods, etc.',
          ro: 'Aparate foto digitale, obiective, trepiede, etc.',
          fr: 'Appareils photo numériques, objectifs, trépieds, etc.',
          de: 'Digitalkameras, Objektive, Stative usw.',
          it: 'Fotocamere digitali, obiettivi, treppiedi, ecc.',
          es: 'Cámaras digitales, lentes, trípodes, etc.',
          ja: 'デジタルカメラ、レンズ、三脚など',
        },
      },
      {
        name: {
          en: 'Home Electronics',
          ro: 'Electronice pentru casă',
          fr: 'Électronique domestique',
          de: 'Haushaltselektronik',
          it: 'Elettronica per la casa',
          es: 'Electrónica para el hogar',
          ja: '家庭用電子機器',
        },
        details: {
          en: 'TVs, DVD players, home theaters, etc.',
          ro: 'Televizoare, playere DVD, home theatre, etc.',
          fr: 'Téléviseurs, lecteurs DVD, home cinémas, etc.',
          de: 'Fernseher, DVD-Player, Heimkinos usw.',
          it: 'TV, lettori DVD, home theater, ecc.',
          es: 'Televisores, reproductores de DVD, teatros en casa, etc.',
          ja: 'テレビ、DVDプレーヤー、ホームシアターなど',
        },
      },
      {
        name: {
          en: 'Audio Equipment',
          ro: 'Echipamente audio',
          fr: 'Équipements audio',
          de: 'Audioausrüstung',
          it: 'Attrezzatura audio',
          es: 'Equipos de audio',
          ja: 'オーディオ機器',
        },
        details: {
          en: 'Speakers, headphones, microphones, etc.',
          ro: 'Boxe, căști, microfoane, etc.',
          fr: 'Haut-parleurs, écouteurs, microphones, etc.',
          de: 'Lautsprecher, Kopfhörer, Mikrofone usw.',
          it: 'Altoparlanti, cuffie, microfoni, ecc.',
          es: 'Altavoces, auriculares, micrófonos, etc.',
          ja: 'スピーカー、ヘッドフォン、マイクなど',
        },
      },
    ],
  },
  {
    name: {
      en: 'Vehicles',
      ro: 'Vehicule',
      fr: 'Véhicules',
      de: 'Fahrzeuge',
      it: 'Veicoli',
      es: 'Vehículos',
      ja: '車両',
    },
    icon: 'vehicles',
    subCategories: [
      {
        name: {
          en: 'Cars',
          ro: 'Mașini',
          fr: 'Voitures',
          de: 'Autos',
          it: 'Auto',
          es: 'Coches',
          ja: '車',
        },
        details: {
          en: 'New and used cars, classic cars',
          ro: 'Mașini noi și second-hand, mașini clasice',
          fr: "Voitures neuves et d'occasion, voitures classiques",
          de: 'Neue und gebrauchte Autos, klassische Autos',
          it: 'Auto nuove e usate, auto classiche',
          es: 'Coches nuevos y usados, coches clásicos',
          ja: '新車と中古車、クラシックカー',
        },
      },
      {
        name: {
          en: 'Motorcycles',
          ro: 'Motociclete',
          fr: 'Motos',
          de: 'Motorräder',
          it: 'Moto',
          es: 'Motocicletas',
          ja: 'バイク',
        },
        details: {
          en: 'New and used motorcycles, scooters',
          ro: 'Motociclete noi și second-hand, scutere',
          fr: "Motos neuves et d'occasion, scooters",
          de: 'Neue und gebrauchte Motorräder, Roller',
          it: 'Moto nuove e usate, scooter',
          es: 'Motocicletas nuevas y usadas, scooters',
          ja: '新車と中古バイク、スクーター',
        },
      },
      {
        name: {
          en: 'Bicycles',
          ro: 'Biciclete',
          fr: 'Vélos',
          de: 'Fahrräder',
          it: 'Biciclette',
          es: 'Bicicletas',
          ja: '自転車',
        },
        details: {
          en: 'Mountain bikes, road bikes, e-bikes',
          ro: 'Biciclete de munte, biciclete de șosea, biciclete electrice',
          fr: 'Vélos de montagne, vélos de route, vélos électriques',
          de: 'Mountainbikes, Rennräder, E-Bikes',
          it: 'Mountain bike, bici da strada, bici elettriche',
          es: 'Bicicletas de montaña, bicicletas de carretera, bicicletas eléctricas',
          ja: 'マウンテンバイク、ロードバイク、電動自転車',
        },
      },
      {
        name: {
          en: 'Boats and Watercraft',
          ro: 'Bărci și ambarcațiuni',
          fr: 'Bateaux et embarcations',
          de: 'Boote und Wasserfahrzeuge',
          it: 'Barche e imbarcazioni',
          es: 'Barcos y embarcaciones',
          ja: 'ボートと水上機',
        },
        details: {
          en: 'Yachts, speedboats, jet skis',
          ro: 'Iahturi, șalupe, jet ski-uri',
          fr: 'Yachts, bateaux à moteur, jet-skis',
          de: 'Yachten, Schnellboote, Jetskis',
          it: 'Yacht, motoscafi, jet ski',
          es: 'Yates, lanchas rápidas, motos de agua',
          ja: 'ヨット、スピードボート、ジェットスキー',
        },
      },
      {
        name: {
          en: 'RV and Campers',
          ro: 'Rulote și autorulote',
          fr: 'Camping-cars et caravanes',
          de: 'Wohnmobile und Camper',
          it: 'Camper e roulotte',
          es: 'Autocaravanas y campers',
          ja: 'RVとキャンパー',
        },
        details: {
          en: 'Recreational vehicles, trailers',
          ro: 'Rulote, autorulote',
          fr: 'Véhicules de loisirs, remorques',
          de: 'Freizeitfahrzeuge, Anhänger',
          it: 'Veicoli ricreativi, rimorchi',
          es: 'Vehículos recreativos, remolques',
          ja: 'レクリエーション車、トレーラー',
        },
      },
    ],
  },
  {
    name: {
      en: 'Real Estate',
      ro: 'Imobiliare',
      fr: 'Immobilier',
      de: 'Immobilien',
      it: 'Immobiliare',
      es: 'Bienes raíces',
      ja: '不動産',
    },
    icon: 'real-estate',
    subCategories: [
      {
        name: {
          en: 'Residential Properties',
          ro: 'Proprietăți rezidențiale',
          fr: 'Propriétés résidentielles',
          de: 'Wohnimmobilien',
          it: 'Proprietà residenziali',
          es: 'Propiedades residenciales',
          ja: '住宅物件',
        },
        details: {
          en: 'Houses, apartments, condos',
          ro: 'Case, apartamente, garsoniere',
          fr: 'Maisons, appartements, condos',
          de: 'Häuser, Wohnungen, Eigentumswohnungen',
          it: 'Case, appartamenti, condomini',
          es: 'Casas, apartamentos, condominios',
          ja: '一戸建て、アパート、マンション',
        },
      },
      {
        name: {
          en: 'Commercial Properties',
          ro: 'Proprietăți comerciale',
          fr: 'Propriétés commerciales',
          de: 'Gewerbeimmobilien',
          it: 'Proprietà commerciali',
          es: 'Propiedades comerciales',
          ja: '商業用物件',
        },
        details: {
          en: 'Office spaces, retail spaces',
          ro: 'Spații de birouri, spații comerciale',
          fr: 'Espaces de bureaux, espaces commerciaux',
          de: 'Büroflächen, Einzelhandelsflächen',
          it: 'Spazi per uffici, spazi commerciali',
          es: 'Espacios de oficina, espacios comerciales',
          ja: 'オフィススペース、小売スペース',
        },
      },
      {
        name: {
          en: 'Land',
          ro: 'Terenuri',
          fr: 'Terrains',
          de: 'Grundstücke',
          it: 'Terreni',
          es: 'Terrenos',
          ja: '土地',
        },
        details: {
          en: 'Agricultural land, plots for development',
          ro: 'Terenuri agricole, parcele pentru dezvoltare',
          fr: 'Terrains agricoles, parcelles pour développement',
          de: 'Landwirtschaftliche Flächen, Entwicklungsgrundstücke',
          it: 'Terreni agricoli, lotti per sviluppo',
          es: 'Terrenos agrícolas, parcelas para desarrollo',
          ja: '農地、開発用地',
        },
      },
      {
        name: {
          en: 'Vacation Properties',
          ro: 'Proprietăți de vacanță',
          fr: 'Propriétés de vacances',
          de: 'Ferienimmobilien',
          it: 'Proprietà per le vacanze',
          es: 'Propiedades de vacaciones',
          ja: '別荘',
        },
        details: {
          en: 'Timeshares, cabins, beach houses',
          ro: 'Proprietăți cu timp împărțit, cabane, case de plajă',
          fr: 'Multipropriétés, cabanes, maisons de plage',
          de: 'Teilzeitnutzungen, Hütten, Strandhäuser',
          it: 'Multiproprietà, cabine, case sulla spiaggia',
          es: 'Tiempos compartidos, cabañas, casas de playa',
          ja: 'タイムシェア、キャビン、ビーチハウス',
        },
      },
      {
        name: {
          en: 'Foreclosures',
          ro: 'Executări silite',
          fr: 'Saisies',
          de: 'Zwangsvollstreckungen',
          it: 'Pignoramenti',
          es: 'Embargos',
          ja: '差し押さえ',
        },
        details: {
          en: 'Bank-owned properties',
          ro: 'Proprietăți deținute de bănci',
          fr: 'Propriétés détenues par des banques',
          de: 'Bankeigene Immobilien',
          it: 'Proprietà di proprietà delle banche',
          es: 'Propiedades propiedad de bancos',
          ja: '銀行所有の物件',
        },
      },
    ],
  },
  {
    name: {
      en: 'Collectibles',
      ro: 'Antichități',
      fr: 'Objets de collection',
      de: 'Sammlerstücke',
      it: 'Collezionabili',
      es: 'Coleccionables',
      ja: 'コレクターズアイテム',
    },
    icon: 'collectibles',
    subCategories: [
      {
        name: {
          en: 'Antiques',
          ro: 'Antichități',
          fr: 'Antiquités',
          de: 'Antiquitäten',
          it: 'Antichità',
          es: 'Antigüedades',
          ja: 'アンティーク',
        },
        details: {
          en: 'Furniture, clocks, art',
          ro: 'Mobilier, ceasuri, artă',
          fr: 'Meubles, horloges, art',
          de: 'Möbel, Uhren, Kunst',
          it: 'Mobili, orologi, arte',
          es: 'Muebles, relojes, arte',
          ja: '家具、時計、アート',
        },
      },
      {
        name: {
          en: 'Stamps',
          ro: 'Timbre',
          fr: 'Timbres',
          de: 'Briefmarken',
          it: 'Francobolli',
          es: 'Sellos',
          ja: '切手',
        },
        details: {
          en: 'Rare stamps, collections',
          ro: 'Timbre rare, colecții',
          fr: 'Timbres rares, collections',
          de: 'Seltene Briefmarken, Sammlungen',
          it: 'Francobolli rari, collezioni',
          es: 'Sellos raros, colecciones',
          ja: '希少な切手、コレクション',
        },
      },
      {
        name: {
          en: 'Sports Memorabilia',
          ro: 'Memorabilie sportivă',
          fr: 'Objets de sport',
          de: 'Sport-Erinnerungsstücke',
          it: 'Memorabilia sportiva',
          es: 'Recuerdos deportivos',
          ja: 'スポーツ記念品',
        },
        details: {
          en: 'Autographs, trading cards, game-worn items',
          ro: 'Autografe, cărți de schimb, articole purtate în jocuri',
          fr: 'Autographes, cartes à collectionner, articles portés en jeu',
          de: 'Autogramme, Sammelkarten, im Spiel getragene Gegenstände',
          it: 'Autografi, carte da collezione, articoli indossati durante il gioco',
          es: 'Autógrafos, tarjetas de intercambio, artículos usados en el juego',
          ja: 'オートグラフ、トレーディングカード、ゲームで着用したアイテム',
        },
      },
      {
        name: {
          en: 'Toys and Games',
          ro: 'Jucării și jocuri',
          fr: 'Jouets et jeux',
          de: 'Spielzeug und Spiele',
          it: 'Giochi e giocattoli',
          es: 'Juguetes y juegos',
          ja: 'おもちゃとゲーム',
        },
        details: {
          en: 'Vintage toys, board games, action figures',
          ro: 'Jucării vechi, jocuri de societate, figurine',
          fr: 'Jouets vintage, jeux de société, figurines',
          de: 'Vintage-Spielzeug, Brettspiele, Actionfiguren',
          it: 'Giocattoli vintage, giochi da tavolo, action figure',
          es: 'Juguetes vintage, juegos de mesa, figuras de acción',
          ja: 'ヴィンテージのおもちゃ、ボードゲーム、アクションフィギュア',
        },
      },
      {
        name: {
          en: 'Coins',
          ro: 'Monede',
          fr: 'Pièces de monnaie',
          de: 'Münzen',
          it: 'Monete',
          es: 'Monedas',
          ja: 'コイン',
        },
        details: {
          en: 'Rare coins, collections',
          ro: 'Monede rare, colecții',
          fr: 'Pièces rares, collections',
          de: 'Seltene Münzen, Sammlungen',
          it: 'Monete rare, collezioni',
          es: 'Monedas raras, colecciones',
          ja: '希少なコイン、コレクション',
        },
      },
    ],
  },
  {
    name: {
      en: 'Fashion and Accessories',
      ro: 'Modă și accesorii',
      fr: 'Mode et accessoires',
      de: 'Mode und Accessoires',
      it: 'Moda e accessori',
      es: 'Moda y accesorios',
      ja: 'ファッションとアクセサリー',
    },
    icon: 'fashion',
    subCategories: [
      {
        name: {
          en: 'Clothing',
          ro: 'Îmbrăcăminte',
          fr: 'Vêtements',
          de: 'Kleidung',
          it: 'Abbigliamento',
          es: 'Ropa',
          ja: '服',
        },
        details: {
          en: 'Designer brands, vintage clothing',
          ro: 'Branduri de designer, îmbrăcăminte vintage',
          fr: 'Marques de créateurs, vêtements vintage',
          de: 'Designermarken, Vintage-Kleidung',
          it: 'Marchi di design, abbigliamento vintage',
          es: 'Marcas de diseñador, ropa vintage',
          ja: 'デザイナーブランド、ヴィンテージ服',
        },
      },
      {
        name: {
          en: 'Shoes',
          ro: 'Încălțăminte',
          fr: 'Chaussures',
          de: 'Schuhe',
          it: 'Scarpe',
          es: 'Zapatos',
          ja: '靴',
        },
        details: {
          en: 'Sneakers, boots, heels',
          ro: 'Teniși, cizme, tocuri',
          fr: 'Baskets, bottes, talons',
          de: 'Turnschuhe, Stiefel, Absätze',
          it: 'Sneakers, stivali, tacchi',
          es: 'Zapatillas, botas, tacones',
          ja: 'スニーカー、ブーツ、ヒール',
        },
      },
      {
        name: {
          en: 'Bags and Luggage',
          ro: 'Genți și bagaje',
          fr: 'Sacs et bagages',
          de: 'Taschen und Gepäck',
          it: 'Borse e bagagli',
          es: 'Bolsos y equipaje',
          ja: 'バッグと荷物',
        },
        details: {
          en: 'Handbags, backpacks, suitcases',
          ro: 'Genți de mână, rucsacuri, valize',
          fr: 'Sacs à main, sacs à dos, valises',
          de: 'Handtaschen, Rucksäcke, Koffer',
          it: 'Borse, zaini, valigie',
          es: 'Bolsos, mochilas, maletas',
          ja: 'ハンドバッグ、バックパック、スーツケース',
        },
      },
      {
        name: {
          en: 'Jewelry',
          ro: 'Bijuterii',
          fr: 'Bijoux',
          de: 'Schmuck',
          it: 'Gioielli',
          es: 'Joyería',
          ja: 'ジュエリー',
        },
        details: {
          en: 'Rings, necklaces, bracelets',
          ro: 'Inele, coliere, brățări',
          fr: 'Bagues, colliers, bracelets',
          de: 'Ringe, Halsketten, Armbänder',
          it: 'Anelli, collane, braccialetti',
          es: 'Anillos, collares, pulseras',
          ja: '指輪、ネックレス、ブレスレット',
        },
      },
      {
        name: {
          en: 'Watches',
          ro: 'Ceasuri',
          fr: 'Montres',
          de: 'Uhren',
          it: 'Orologi',
          es: 'Relojes',
          ja: '時計',
        },
        details: {
          en: 'Luxury watches, smartwatches',
          ro: 'Ceasuri de lux, ceasuri inteligente',
          fr: 'Montres de luxe, montres connectées',
          de: 'Luxusuhren, Smartwatches',
          it: 'Orologi di lusso, smartwatch',
          es: 'Relojes de lujo, relojes inteligentes',
          ja: '高級時計、スマートウォッチ',
        },
      },
      {
        name: {
          en: 'Accessories',
          ro: 'Accesorii',
          fr: 'Accessoires',
          de: 'Accessoires',
          it: 'Accessori',
          es: 'Accesorios',
          ja: 'アクセサリー',
        },
        details: {
          en: 'Hats, scarves, belts',
          ro: 'Pălării, eșarfe, curele',
          fr: 'Chapeaux, écharpes, ceintures',
          de: 'Hüte, Schals, Gürtel',
          it: 'Cappelli, sciarpe, cinture',
          es: 'Sombreros, bufandas, cinturones',
          ja: '帽子、スカーフ、ベルト',
        },
      },
    ],
  },
  {
    name: {
      en: 'Home and Garden',
      ro: 'Casă și grădină',
      fr: 'Maison et jardin',
      de: 'Haus und Garten',
      it: 'Casa e giardino',
      es: 'Hogar y jardín',
      ja: 'ホームとガーデン',
    },
    icon: 'garden',
    subCategories: [
      {
        name: {
          en: 'Furniture',
          ro: 'Mobilier',
          fr: 'Meubles',
          de: 'Möbel',
          it: 'Mobili',
          es: 'Muebles',
          ja: '家具',
        },
        details: {
          en: 'Sofas, tables, beds',
          ro: 'Canapele, mese, paturi',
          fr: 'Canapés, tables, lits',
          de: 'Sofas, Tische, Betten',
          it: 'Divani, tavoli, letti',
          es: 'Sofás, mesas, camas',
          ja: 'ソファ、テーブル、ベッド',
        },
      },
      {
        name: {
          en: 'Home Decor',
          ro: 'Decorațiuni interioare',
          fr: 'Décoration intérieure',
          de: 'Innendekoration',
          it: 'Arredamento',
          es: 'Decoración del hogar',
          ja: 'ホームデコレーション',
        },
        details: {
          en: 'Rugs, curtains, wall art',
          ro: 'Covoare, perdele, tablouri',
          fr: 'Tapis, rideaux, art mural',
          de: 'Teppiche, Vorhänge, Wandkunst',
          it: 'Tappeti, tende, arte murale',
          es: 'Alfombras, cortinas, arte mural',
          ja: 'ラグ、カーテン、壁のアート',
        },
      },
      {
        name: {
          en: 'Kitchenware',
          ro: 'Veselă',
          fr: 'Articles de cuisine',
          de: 'Küchenutensilien',
          it: 'Articoli da cucina',
          es: 'Utensilios de cocina',
          ja: 'キッチン用品',
        },
        details: {
          en: 'Cookware, utensils, appliances',
          ro: 'Vase, ustensile, electrocasnice',
          fr: 'Batterie de cuisine, ustensiles, appareils',
          de: 'Kochgeschirr, Utensilien, Geräte',
          it: 'Pentole, utensili, elettrodomestici',
          es: 'Utensilios de cocina, utensilios, electrodomésticos',
          ja: '調理器具、器具、電化製品',
        },
      },
      {
        name: {
          en: 'Gardening',
          ro: 'Grădinărit',
          fr: 'Jardinage',
          de: 'Gartenarbeit',
          it: 'Giardinaggio',
          es: 'Jardinería',
          ja: '園芸',
        },
        details: {
          en: 'Plants, tools, outdoor furniture',
          ro: 'Plante, unelte, mobilier de exterior',
          fr: "Plantes, outils, meubles d'extérieur",
          de: 'Pflanzen, Werkzeuge, Gartenmöbel',
          it: 'Piante, attrezzi, mobili da esterno',
          es: 'Plantas, herramientas, muebles de exterior',
          ja: '植物、道具、屋外用家具',
        },
      },
      {
        name: {
          en: 'DIY and Tools',
          ro: 'DIY și scule',
          fr: 'Bricolage et outils',
          de: 'Heimwerken und Werkzeuge',
          it: 'Fai da te e utensili',
          es: 'Bricolaje y herramientas',
          ja: 'DIYとツール',
        },
        details: {
          en: 'Power tools, hand tools, building materials',
          ro: 'Unelte electrice, unelte manuale, materiale de construcție',
          fr: 'Outils électriques, outils à main, matériaux de construction',
          de: 'Elektrowerkzeuge, Handwerkzeuge, Baumaterialien',
          it: 'Utensili elettrici, utensili manuali, materiali da costruzione',
          es: 'Herramientas eléctricas, herramientas manuales, materiales de construcción',
          ja: '電動工具、手動工具、建築材料',
        },
      },
      {
        name: {
          en: 'Home Improvement',
          ro: 'Îmbunătățiri pentru casă',
          fr: 'Améliorations de la maison',
          de: 'Heimverbesserung',
          it: 'Miglioramenti della casa',
          es: 'Mejoras para el hogar',
          ja: 'ホームインプルーブメント',
        },
        details: {
          en: 'Lighting, flooring, plumbing',
          ro: 'Iluminat, pardoseli, instalații sanitare',
          fr: 'Éclairage, revêtements de sol, plomberie',
          de: 'Beleuchtung, Bodenbeläge, Sanitärinstallationen',
          it: 'Illuminazione, pavimenti, impianti idraulici',
          es: 'Iluminación, suelos, fontanería',
          ja: '照明、床材、配管',
        },
      },
      {
        name: {
          en: 'Tools',
          ro: 'Scule',
          fr: 'Outils',
          de: 'Werkzeuge',
          it: 'Utensili',
          es: 'Herramientas',
          ja: 'ツール',
        },
        details: {
          en: 'Power tools, hand tools, building materials',
          ro: 'Unelte electrice, unelte manuale, materiale de construcție',
          fr: 'Outils électriques, outils à main, matériaux de construction',
          de: 'Elektrowerkzeuge, Handwerkzeuge, Baumaterialien',
          it: 'Utensili elettrici, utensili manuali, materiali da costruzione',
          es: 'Herramientas eléctricas, herramientas manuales, materiales de construcción',
          ja: '電動工具、手動工具、建築材料',
        },
      },
    ],
  },
  {
    name: {
      en: 'Art',
      ro: 'Artă',
      fr: 'Art',
      de: 'Kunst',
      it: 'Arte',
      es: 'Arte',
      ja: 'アート',
    },
    icon: 'art',
    subCategories: [
      {
        name: {
          en: 'Paintings',
          ro: 'Picturi',
          fr: 'Peintures',
          de: 'Gemälde',
          it: 'Dipinti',
          es: 'Pinturas',
          ja: '絵画',
        },
        details: {
          en: 'Oil paintings, watercolors, acrylics',
          ro: 'Picturi în ulei, acuarelă, acrilice',
          fr: "Peintures à l'huile, aquarelles, acryliques",
          de: 'Ölgemälde, Aquarelle, Acrylbilder',
          it: 'Dipinti a olio, acquerelli, acrilici',
          es: 'Pinturas al óleo, acuarelas, acrílicos',
          ja: '油絵、水彩画、アクリル画',
        },
      },
      {
        name: {
          en: 'Sculptures',
          ro: 'Sculpturi',
          fr: 'Sculptures',
          de: 'Skulpturen',
          it: 'Sculture',
          es: 'Esculturas',
          ja: '彫刻',
        },
        details: {
          en: 'Bronze sculptures, wood carvings',
          ro: 'Sculpturi din bronz, sculpturi din lemn',
          fr: 'Sculptures en bronze, sculptures sur bois',
          de: 'Bronzeskulpturen, Holzschnitzereien',
          it: 'Sculture in bronzo, intagli in legno',
          es: 'Esculturas de bronce, tallas de madera',
          ja: 'ブロンズ彫刻、木彫り',
        },
      },
      {
        name: {
          en: 'Prints',
          ro: 'Reproducții',
          fr: 'Impressions',
          de: 'Drucke',
          it: 'Stampe',
          es: 'Impresiones',
          ja: 'プリント',
        },
        details: {
          en: 'Limited edition prints, posters',
          ro: 'Reproducții în ediție limitată, postere',
          fr: 'Impressions en édition limitée, affiches',
          de: 'Drucke in limitierter Auflage, Poster',
          it: 'Stampe in edizione limitata, poster',
          es: 'Impresiones de edición limitada, carteles',
          ja: '限定版プリント、ポスター',
        },
      },
      {
        name: {
          en: 'Photography',
          ro: 'Fotografie',
          fr: 'Photographie',
          de: 'Fotografie',
          it: 'Fotografia',
          es: 'Fotografía',
          ja: '写真',
        },
        details: {
          en: 'Fine art photography, prints',
          ro: 'Fotografie de artă, reproduceri',
          fr: "Photographie d'art, impressions",
          de: 'Fine-Art-Fotografie, Drucke',
          it: "Fotografia d'arte, stampe",
          es: 'Fotografía artística, impresiones',
          ja: '美術写真、プリント',
        },
      },
      {
        name: {
          en: 'Mixed Media',
          ro: 'Artă mixtă',
          fr: 'Art mixte',
          de: 'Mixed Media',
          it: 'Arte mista',
          es: 'Arte mixta',
          ja: 'ミクストメディア',
        },
        details: {
          en: 'Collages, assemblages, installations',
          ro: 'Colaje, asamblaje, instalații',
          fr: 'Collages, assemblages, installations',
          de: 'Collagen, Assemblagen, Installationen',
          it: 'Collage, assemblaggi, installazioni',
          es: 'Collages, ensamblajes, instalaciones',
          ja: 'コラージュ、アッサンブラージュ、インスタレーション',
        },
      },
      {
        name: {
          en: 'Digital Art',
          ro: 'Artă digitală',
          fr: 'Art numérique',
          de: 'Digitale Kunst',
          it: 'Arte digitale',
          es: 'Arte digital',
          ja: 'デジタルアート',
        },
        details: {
          en: 'NFTs, Digital paintings, 3D art',
          ro: 'NFT-uri, picturi digitale, artă 3D',
          fr: 'NFT, peintures numériques, art 3D',
          de: 'NFTs, digitale Gemälde, 3D-Kunst',
          it: 'NFT, dipinti digitali, arte 3D',
          es: 'NFT, pinturas digitales, arte 3D',
          ja: 'NFT、デジタルペインティング、3Dアート',
        },
      },
    ],
  },
  {
    name: {
      en: 'Toys and Games',
      ro: 'Jucării și jocuri',
      fr: 'Jouets et jeux',
      de: 'Spielzeug und Spiele',
      it: 'Giochi e giocattoli',
      es: 'Juguetes y juegos',
      ja: 'おもちゃとゲーム',
    },
    icon: 'toys',
    subCategories: [
      {
        name: {
          en: 'Action Figures',
          ro: 'Figurine',
          fr: 'Figurines',
          de: 'Actionfiguren',
          it: 'Action figure',
          es: 'Figuras de acción',
          ja: 'アクションフィギュア',
        },
        details: {
          en: 'Superheroes, movie characters, anime',
          ro: 'Supereroi, personaje de film, anime',
          fr: 'Super-héros, personnages de films, anime',
          de: 'Superhelden, Filmcharaktere, Anime',
          it: 'Supereroi, personaggi di film, anime',
          es: 'Superhéroes, personajes de películas, anime',
          ja: 'スーパーヒーロー、映画キャラクター、アニメ',
        },
      },
      {
        name: {
          en: 'Board Games',
          ro: 'Jocuri de societate',
          fr: 'Jeux de société',
          de: 'Brettspiele',
          it: 'Giochi da tavolo',
          es: 'Juegos de mesa',
          ja: 'ボードゲーム',
        },
        details: {
          en: 'Classic games, strategy games, party games',
          ro: 'Jocuri clasice, jocuri de strategie, jocuri de petrecere',
          fr: 'Jeux classiques, jeux de stratégie, jeux de société',
          de: 'Klassische Spiele, Strategiespiele, Partyspiele',
          it: 'Giochi classici, giochi di strategia, giochi di società',
          es: 'Juegos clásicos, juegos de estrategia, juegos de fiesta',
          ja: 'クラシックゲーム、戦略ゲーム、パーティーゲーム',
        },
      },
      {
        name: {
          en: 'Video Games',
          ro: 'Jocuri video',
          fr: 'Jeux vidéo',
          de: 'Videospiele',
          it: 'Videogiochi',
          es: 'Videojuegos',
          ja: 'ビデオゲーム',
        },
        details: {
          en: 'Consoles, games, accessories',
          ro: 'Console, jocuri, accesorii',
          fr: 'Consoles, jeux, accessoires',
          de: 'Konsolen, Spiele, Zubehör',
          it: 'Console, giochi, accessori',
          es: 'Consolas, juegos, accesorios',
          ja: 'コンソール、ゲーム、アクセサリー',
        },
      },
      {
        name: {
          en: 'Puzzles',
          ro: 'Puzzle-uri',
          fr: 'Puzzles',
          de: 'Puzzles',
          it: 'Puzzle',
          es: 'Rompecabezas',
          ja: 'パズル',
        },
        details: {
          en: 'Jigsaw puzzles, brain teasers',
          ro: 'Puzzle-uri, jocuri de logică',
          fr: 'Puzzles, casse-têtes',
          de: 'Puzzles, Denksportaufgaben',
          it: 'Puzzle, rompicapo',
          es: 'Rompecabezas, juegos de ingenio',
          ja: 'ジグソーパズル、脳トレ',
        },
      },
      {
        name: {
          en: 'LEGO Sets',
          ro: 'Seturi LEGO',
          fr: 'Ensembles LEGO',
          de: 'LEGO-Sets',
          it: 'Set LEGO',
          es: 'Sets de LEGO',
          ja: 'レゴセット',
        },
        details: {
          en: 'New and vintage LEGO sets',
          ro: 'Seturi LEGO noi și vechi',
          fr: 'Ensembles LEGO neufs et vintage',
          de: 'Neue und alte LEGO-Sets',
          it: 'Set LEGO nuovi e vintage',
          es: 'Sets de LEGO nuevos y vintage',
          ja: '新旧のレゴセット',
        },
      },
    ],
  },
  {
    name: {
      en: 'Industrial Equipment',
      ro: 'Echipamente industriale',
      fr: 'Équipements industriels',
      de: 'Industrieausrüstung',
      it: 'Attrezzature industriali',
      es: 'Equipos industriales',
      ja: '産業機器',
    },
    icon: 'industrial',
    subCategories: [
      {
        name: {
          en: 'Manufacturing Equipment',
          ro: 'Echipamente de producție',
          fr: 'Équipements de fabrication',
          de: 'Fertigungsanlagen',
          it: 'Attrezzature di produzione',
          es: 'Equipos de fabricación',
          ja: '製造設備',
        },
        details: {
          en: 'Machinery, tools, supplies',
          ro: 'Mașini, unelte, materiale',
          fr: 'Machines, outils, fournitures',
          de: 'Maschinen, Werkzeuge, Vorräte',
          it: 'Macchinari, utensili, forniture',
          es: 'Maquinaria, herramientas, suministros',
          ja: '機械、工具、用品',
        },
      },
      {
        name: {
          en: 'Construction Equipment',
          ro: 'Echipamente de construcții',
          fr: 'Équipements de construction',
          de: 'Baumaschinen',
          it: 'Attrezzature per costruzioni',
          es: 'Equipos de construcción',
          ja: '建設機械',
        },
        details: {
          en: 'Excavators, cranes, loaders',
          ro: 'Excavatoare, macarale, încărcătoare',
          fr: 'Excavatrices, grues, chargeuses',
          de: 'Bagger, Kräne, Lader',
          it: 'Escavatori, gru, caricatori',
          es: 'Excavadoras, grúas, cargadoras',
          ja: '掘削機、クレーン、ローダー',
        },
      },
      {
        name: {
          en: 'Agricultural Equipment',
          ro: 'Echipamente agricole',
          fr: 'Équipements agricoles',
          de: 'Landwirtschaftliche Geräte',
          it: 'Attrezzature agricole',
          es: 'Equipos agrícolas',
          ja: '農業機器',
        },
        details: {
          en: 'Tractors, harvesters, irrigation systems',
          ro: 'Tractoare, combine, sisteme de irigații',
          fr: "Tracteurs, moissonneuses, systèmes d'irrigation",
          de: 'Traktoren, Mähdrescher, Bewässerungssysteme',
          it: 'Trattori, mietitrici, sistemi di irrigazione',
          es: 'Tractores, cosechadoras, sistemas de riego',
          ja: 'トラクター、収穫機、灌漑システム',
        },
      },
      {
        name: {
          en: 'Food Processing Equipment',
          ro: 'Echipamente de procesare a alimentelor',
          fr: 'Équipements de transformation alimentaire',
          de: 'Lebensmittelverarbeitungsgeräte',
          it: 'Attrezzature per la lavorazione degli alimenti',
          es: 'Equipos de procesamiento de alimentos',
          ja: '食品加工機械',
        },
        details: {
          en: 'Mixers, ovens, packaging machines',
          ro: 'Mixer, cuptoare, mașini de ambalat',
          fr: "Mixeurs, fours, machines d'emballage",
          de: 'Mischer, Öfen, Verpackungsmaschinen',
          it: "Miscelatori, forni, macchine per l'imballaggio",
          es: 'Mezcladores, hornos, máquinas de embalaje',
          ja: 'ミキサー、オーブン、包装機械',
        },
      },
      {
        name: {
          en: 'Medical Equipment',
          ro: 'Echipamente medicale',
          fr: 'Équipements médicaux',
          de: 'Medizinische Geräte',
          it: 'Attrezzature mediche',
          es: 'Equipos médicos',
          ja: '医療機器',
        },
        details: {
          en: 'Imaging machines, surgical tools, lab equipment',
          ro: 'Aparate de imagistică, instrumente chirurgicale, echipamente de laborator',
          fr: "Machines d'imagerie, outils chirurgicaux, équipements de laboratoire",
          de: 'Bildgebende Geräte, chirurgische Werkzeuge, Laborausrüstung',
          it: 'Macchine per imaging, strumenti chirurgici, attrezzature di laboratorio',
          es: 'Máquinas de imagen, herramientas quirúrgicas, equipos de laboratorio',
          ja: '画像機器、手術器具、実験室機器',
        },
      },
      {
        name: {
          en: 'Restaurant Equipment',
          ro: 'Echipamente pentru restaurante',
          fr: 'Équipements de restaurant',
          de: 'Restaurantgeräte',
          it: 'Attrezzature per ristoranti',
          es: 'Equipos de restaurante',
          ja: 'レストラン機器',
        },
        details: {
          en: 'Ovens, refrigerators, dishwashers',
          ro: 'Cuptoare, frigidere, mașini de spălat vase',
          fr: 'Fours, réfrigérateurs, lave-vaisselle',
          de: 'Öfen, Kühlschränke, Geschirrspüler',
          it: 'Forni, frigoriferi, lavastoviglie',
          es: 'Hornos, refrigeradores, lavavajillas',
          ja: 'オーブン、冷蔵庫、食器洗い機',
        },
      },
      {
        name: {
          en: 'Office Equipment',
          ro: 'Echipamente de birou',
          fr: 'Équipements de bureau',
          de: 'Büroausstattung',
          it: 'Attrezzature per ufficio',
          es: 'Equipos de oficina',
          ja: 'オフィス機器',
        },
        details: {
          en: 'Printers, copiers, scanners',
          ro: 'Imprimante, copiatoare, scanere',
          fr: 'Imprimantes, copieurs, scanners',
          de: 'Drucker, Kopierer, Scanner',
          it: 'Stampanti, fotocopiatrici, scanner',
          es: 'Impresoras, fotocopiadoras, escáneres',
          ja: 'プリンター、コピー機、スキャナー',
        },
      },
    ],
  },
  {
    name: {
      en: 'Services',
      ro: 'Servicii',
      fr: 'Services',
      de: 'Dienstleistungen',
      it: 'Servizi',
      es: 'Servicios',
      ja: 'サービス',
    },
    icon: 'services',
    subCategories: [
      {
        name: {
          en: 'Automotive Services',
          ro: 'Servicii auto',
          fr: 'Services automobiles',
          de: 'Kfz-Dienstleistungen',
          it: 'Servizi automobilistici',
          es: 'Servicios automotrices',
          ja: '自動車サービス',
        },
        details: {
          en: 'Car repair, car wash, towing',
          ro: 'Reparații auto, spălătorii auto, tractări',
          fr: 'Réparation automobile, lavage de voiture, remorquage',
          de: 'Autoreparatur, Autowäsche, Abschleppdienst',
          it: 'Riparazione auto, autolavaggio, traino',
          es: 'Reparación de automóviles, lavado de coches, remolque',
          ja: '車の修理、洗車、牽引',
        },
      },
      {
        name: {
          en: 'Home Services',
          ro: 'Servicii pentru casă',
          fr: 'Services à domicile',
          de: 'Haushaltsdienstleistungen',
          it: 'Servizi domestici',
          es: 'Servicios para el hogar',
          ja: 'ホームサービス',
        },
        details: {
          en: 'Cleaning, plumbing, electrical',
          ro: 'Curățenie, instalații sanitare, electrice',
          fr: 'Nettoyage, plomberie, électricité',
          de: 'Reinigung, Sanitär, Elektro',
          it: 'Pulizia, idraulica, elettricità',
          es: 'Limpieza, fontanería, electricidad',
          ja: '清掃、配管、電気',
        },
      },
      {
        name: {
          en: 'Beauty and Wellness',
          ro: 'Frumusețe și wellness',
          fr: 'Beauté et bien-être',
          de: 'Schönheit und Wellness',
          it: 'Bellezza e benessere',
          es: 'Belleza y bienestar',
          ja: '美容とウェルネス',
        },
        details: {
          en: 'Hair salons, spas, massage',
          ro: 'Saloane de coafură, spa-uri, masaj',
          fr: 'Salons de coiffure, spas, massages',
          de: 'Friseursalons, Spas, Massagen',
          it: 'Saloni di bellezza, spa, massaggi',
          es: 'Salones de belleza, spas, masajes',
          ja: 'ヘアサロン、スパ、マッサージ',
        },
      },
      {
        name: {
          en: 'Event Services',
          ro: 'Servicii pentru evenimente',
          fr: 'Services événementiels',
          de: 'Veranstaltungsdienste',
          it: 'Servizi per eventi',
          es: 'Servicios para eventos',
          ja: 'イベントサービス',
        },
        details: {
          en: 'Catering, photography, event planning',
          ro: 'Catering, fotografie, planificare de evenimente',
          fr: "Restauration, photographie, planification d'événements",
          de: 'Catering, Fotografie, Veranstaltungsplanung',
          it: 'Catering, fotografia, pianificazione di eventi',
          es: 'Catering, fotografía, planificación de eventos',
          ja: 'ケータリング、写真撮影、イベント企画',
        },
      },
      {
        name: {
          en: 'Computer and Tech Help',
          ro: 'Ajutor pentru calculatoare și tehnologie',
          fr: 'Aide informatique et technologique',
          de: 'Computer- und Technikhilfe',
          it: 'Aiuto per computer e tecnologia',
          es: 'Ayuda para computadoras y tecnología',
          ja: 'コンピューターと技術支援',
        },
        details: {
          en: 'IT support, computer repair, web design',
          ro: 'Suport IT, reparații de calculatoare, web design',
          fr: "Support informatique, réparation d'ordinateurs, conception web",
          de: 'IT-Support, Computerreparatur, Webdesign',
          it: 'Supporto IT, riparazione computer, web design',
          es: 'Soporte informático, reparación de computadoras, diseño web',
          ja: 'ITサポート、コンピューター修理、ウェブデザイン',
        },
      },
      {
        name: {
          en: 'Financial Services',
          ro: 'Servicii financiare',
          fr: 'Services financiers',
          de: 'Finanzdienstleistungen',
          it: 'Servizi finanziari',
          es: 'Servicios financieros',
          ja: '金融サービス',
        },
        details: {
          en: 'Accounting, tax preparation, financial planning',
          ro: 'Contabilitate, pregătirea impozitelor, planificare financiară',
          fr: 'Comptabilité, préparation fiscale, planification financière',
          de: 'Buchhaltung, Steuererklärung, Finanzplanung',
          it: 'Contabilità, preparazione fiscale, pianificazione finanziaria',
          es: 'Contabilidad, preparación de impuestos, planificación financiera',
          ja: '会計、税務準備、財務計画',
        },
      },
      {
        name: {
          en: 'Legal Services',
          ro: 'Servicii juridice',
          fr: 'Services juridiques',
          de: 'Rechtsdienstleistungen',
          it: 'Servizi legali',
          es: 'Servicios legales',
          ja: '法務サービス',
        },
        details: {
          en: 'Lawyers, notaries, legal advice',
          ro: 'Avocați, notari, consultanță juridică',
          fr: 'Avocats, notaires, conseils juridiques',
          de: 'Anwälte, Notare, Rechtsberatung',
          it: 'Avvocati, notai, consulenza legale',
          es: 'Abogados, notarios, asesoramiento legal',
          ja: '弁護士、公証人、法律相談',
        },
      },
    ],
  },
]

export async function up({
  context: queryInterface,
}: {
  context: sequelize.QueryInterface
}) {
  const transaction = await queryInterface.sequelize.transaction()

  try {
    for (const category of CATEGORIES) {
      const createdCategory = await Category.create(category, { transaction })

      if (category.subCategories) {
        for (const subCategory of category.subCategories) {
          await Category.create(
            { ...subCategory, parentCategoryId: createdCategory.id },
            { transaction }
          )
        }
      }
    }

    await transaction.commit()
  } catch (error) {
    console.error(error)
    await transaction.rollback()
    throw error
  }
}

export async function down({
  context: queryInterface,
}: {
  context: sequelize.QueryInterface
}) {
  const transaction = await queryInterface.sequelize.transaction()

  try {
    await queryInterface.bulkDelete(DATABASE_MODELS.CATEGORIES, null, {
      transaction,
    })

    await transaction.commit()
  } catch (error) {
    await transaction.rollback()
    throw error
  }
}
