import 'package:biddo/core/controllers/account.dart';
import 'package:biddo/core/controllers/ads.dart';
import 'package:biddo/core/controllers/auction.dart';
import 'package:biddo/core/controllers/auth.dart';
import 'package:biddo/core/controllers/bid.dart';
import 'package:biddo/core/controllers/comment.dart';
import 'package:biddo/core/controllers/currencies.dart';
import 'package:biddo/core/controllers/settings.dart';
import 'package:biddo/core/controllers/favourites.dart';
import 'package:biddo/core/controllers/filter.dart';
import 'package:biddo/core/controllers/flash.dart';
import 'package:biddo/core/controllers/last_seen_auctions.dart';
import 'package:biddo/core/controllers/location.dart';
import 'package:biddo/core/controllers/map_auctions.dart';
import 'package:biddo/core/controllers/maps.dart';
import 'package:biddo/core/controllers/notifications.dart';
import 'package:biddo/core/controllers/payments.dart';
import 'package:biddo/core/controllers/review.dart';
import 'package:biddo/core/controllers/socket.dart';
import 'package:biddo/core/controllers/terms.dart';
import 'package:biddo/core/repositories/account.dart';
import 'package:biddo/core/repositories/ads.dart';
import 'package:biddo/core/repositories/auction.dart';
import 'package:biddo/core/repositories/bid.dart';
import 'package:biddo/core/repositories/categories.dart';
import 'package:biddo/core/repositories/chat.dart';
import 'package:biddo/core/repositories/comment.dart';
import 'package:biddo/core/repositories/settings.dart';
import 'package:biddo/core/repositories/favourites.dart';
import 'package:biddo/core/repositories/main.dart';
import 'package:biddo/core/repositories/notification.dart';
import 'package:biddo/core/repositories/payment.dart';
import 'package:biddo/core/repositories/report.dart';
import 'package:biddo/core/services/auth.dart';
import 'package:biddo/core/services/image_compress.dart';
import 'package:biddo/core/services/lang_detector.dart';
import 'package:biddo/core/services/socket.dart';
import 'package:biddo/core/controllers/theme.dart';
import 'package:get/get.dart';

import 'controllers/ai.dart';
import 'controllers/categories.dart';
import 'controllers/chat.dart';
import 'controllers/followers.dart';
import 'controllers/image_picker.dart';
import 'controllers/main.dart';
import 'controllers/search.dart';
import 'controllers/secured.dart';
import 'navigator.dart';
import 'repositories/ai.dart';
import 'repositories/base.dart';
import 'repositories/filter.dart';
import 'repositories/followers.dart';
import 'repositories/last_seen_auctions.dart';
import 'repositories/review.dart';
import 'repositories/search_history.dart';
import 'services/connectivity.dart';

void setupGetxData() {
  Get.put(SecuredController());
  Get.put(FlashController());
  Get.put(NavigatorService());
  Get.put(ConnectivityService());
  Get.put(ImageCompressService());
  Get.put(LanguageDetectorService());
  Get.put(ThemeController());
  Get.put(Api());

  Get.put(CategoriesRepository());
  Get.put(AccountsRepository());
  Get.put(FavouriteRepository());
  Get.put(MainRepository());
  Get.put(NotificationRepository());
  Get.put(AuctionRepository());
  Get.put(BidRepository());
  Get.put(LastSeenAuctionsRepository());
  Get.put(SearchHistoryRepository());
  Get.put(FiltersRepository());
  Get.put(ReportsRepository());
  Get.put(ReviewRepository());
  Get.put(FollowersRepository());
  Get.put(ChatRepository());
  Get.put(PaymentRepository());
  Get.put(SettingsRepository());
  Get.put(AdsRepository());
  Get.put(CommentRepository());
  Get.put(AIRepository());

  Get.put(SettingsController());
  Get.put(LocationController());
  Get.put(ImagePickerController());
  Get.put(AccountController());
  Get.put(AuthController());
  Get.put(CurrenciesController());

  Get.put(SocketService());
  Get.put(SocketController());

  Get.put(ChatController());
  Get.put(CategoriesController());
  Get.put(AuthService());
  Get.put(FavouritesController());
  Get.put(TermsAndConditionController());
  Get.put(NotificationsController());
  Get.put(MapsController());
  Get.put(LastSeenAuctionsController());
  Get.put(SearchController());
  Get.put(FilterController());
  Get.put(ReviewsController());
  Get.put(FollowersController());
  Get.put(MapAuctionsController());
  Get.put(AuctionController());
  Get.put(PaymentsController());
  Get.put(MainController());
  Get.put(BidController());
  Get.put(AdsController());
  Get.put(CommentsController());
  Get.put(AiController());
}
